### PR TITLE
nbgit did not compile with Netbeans 6.9, this commit fix the issue

### PR DESCRIPTION
**Pull request by eskatos**
The only class affected is CheckoutBuilder.

### CODE REVIEW

**Comment by thegass** [comment]
fixed my build-errors with netbeans 7.

**Comment by eskatos** [comment]
I suppose that Netbeans 7.0 comes with out of the box git support, why would you use nbgit with nb7 ?

**Comment by thegass** [comment]
thx for the hint. didn't know there is a installable plugin for 7.0 (not real out-of-the-box, I had to install it via the plugin-manager).

**Comment by eskatos** [comment]
Glad it helped you. Happy coding :)

**Comment by eskatos** [comment]
This is 8 years old, closing

**Pull request closed without merging**
